name: Add App Installers to Release

on:
  push:
    tags:
      - '*'

jobs:

  build-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, test, package
      run: |
        npm install
        npm run build --if-present
        npm test
        npm run package:mac
      env:
        CI: true
    - name: add app to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/installers/neuro-task.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, test, package
      run: |
        npm install
        npm run build --if-present
        npm test
        npm run package:linux
      env:
        CI: true
    - name: what is in dist/installers
      run: |
        ls -l dist/installers
    - name: add app to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/installers/neuro-task_0.1.0_x64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: npm package
      run: |
        npm run package:windows
      env:
        CI: true
    - name: what is in dist/installers
      run: dir dist
    - name: add app to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/installers/neuro-task-0.0.1-setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
