name: CI Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/nodejs.yml'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: npm install
      env:
        CI: true
    - name: npm build
      run: npm run build
      env:
        CI: true
    - name: npm test
      run: npm test
      env:
        CI: true
    - name: package electron - windows
      if: startsWith(matrix.os, 'windows')
      run: npm run package:windows
    - name: package electron - linux
      if: startsWith(matrix.os, 'ubuntu')
      run: npm run package:linux
    - name: package electron - mac
      if: startsWith(matrix.os, 'mac')
      run: npm run package:mac
    - uses: actions/upload-artifact@master
      if: startsWith(matrix.os, 'mac')
      with:
        name: mac-installer
        path: dist/neuro-task-0.1.0.dmg
    - uses: actions/upload-artifact@master
      if: startsWith(matrix.os, 'ubuntu')
      with:
        name: linux-installer
        path: dist/installers/neuro-task_0.1.0_x64.deb
    - uses: actions/upload-artifact@master
      if: startsWith(matrix.os, 'windows')
      with:
        name: win-installer
        path: dist/installers/neuro_task-0.1.0-setup.exe
